# Comix Server Docker Compose Configuration
version: '3.8'

services:
  comix-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    container_name: comix-server
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "${COMIX_SERVER_PORT:-31257}:31257"
    
    # Volume mounts
    volumes:
      # Mount your manga collection (read-only for security)
      - "${MANGA_DIRECTORY:-../manga}:/manga:ro"
      # Optional: Mount config directory
      - "${CONFIG_DIRECTORY:-../config}:/app/config:ro"
    
    # Environment variables
    environment:
      # Server configuration
      - COMIX_MANGA_DIRECTORY=/manga
      - COMIX_SERVER_HOST=0.0.0.0
      - COMIX_SERVER_PORT=31257
      - COMIX_DEBUG_MODE=${DEBUG_MODE:-false}
      - COMIX_LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # File filtering (optional customization)
      - COMIX_HIDDEN_FILES=${HIDDEN_FILES:-}
      - COMIX_HIDDEN_PATTERNS=${HIDDEN_PATTERNS:-}
      
      # Supported formats (optional customization)
      - COMIX_IMAGE_EXTENSIONS=${IMAGE_EXTENSIONS:-}
      - COMIX_ARCHIVE_EXTENSIONS=${ARCHIVE_EXTENSIONS:-}
    
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:31257/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Network configuration
    networks:
      - comix-network

# Network definition
networks:
  comix-network:
    driver: bridge
    name: comix-network

# Optional: Volume definitions for persistent data
volumes:
  manga-data:
    driver: local
    name: comix-manga-data
  config-data:
    driver: local
    name: comix-config-data