# Comix Server Production Docker Compose Configuration
# 프로덕션 환경용 설정 - 보안 및 성능 최적화

version: '3.8'

services:
  comix-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    image: comix-server:latest
    container_name: comix-server
    restart: unless-stopped
    
    # 포트 매핑
    ports:
      - "${COMIX_SERVER_PORT:-31257}:31257"
    
    # 볼륨 마운트
    volumes:
      # 만화 컬렉션 마운트 (보안을 위해 읽기 전용)
      - "${MANGA_DIRECTORY}:/comix:ro"
      # 선택사항: 설정 디렉토리 마운트
      - "${CONFIG_DIRECTORY:-./config}:/app/config:ro"
      # 선택사항: 로그 디렉토리 마운트
      - "${LOG_DIRECTORY:-./logs}:/app/logs:rw"
    
    # 환경 변수
    environment:
      # 서버 기본 설정
      - COMIX_MANGA_DIRECTORY=/comix
      - COMIX_SERVER_HOST=0.0.0.0
      - COMIX_SERVER_PORT=31257
      - COMIX_DEBUG_MODE=${DEBUG_MODE:-false}
      - COMIX_LOG_LEVEL=${LOG_LEVEL:-INFO}
      
      # 파일 필터링 (선택사항)
      - COMIX_HIDDEN_FILES=${HIDDEN_FILES:-.DS_Store,Thumbs.db,@eaDir}
      - COMIX_HIDDEN_PATTERNS=${HIDDEN_PATTERNS:-__MACOSX}
      
      # 지원 파일 형식 (선택사항)
      - COMIX_IMAGE_EXTENSIONS=${IMAGE_EXTENSIONS:-jpg,jpeg,png,gif,bmp,webp}
      - COMIX_ARCHIVE_EXTENSIONS=${ARCHIVE_EXTENSIONS:-zip,rar,cbz,cbr}
      
      # 성능 설정
      - COMIX_MAX_IMAGE_SIZE=${MAX_IMAGE_SIZE:-10485760}  # 10MB
      - COMIX_CACHE_SIZE=${CACHE_SIZE:-100}
    
    # 리소스 제한 (필요에 따라 조정)
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-1G}
          cpus: ${CPU_LIMIT:-2.0}
        reservations:
          memory: ${MEMORY_RESERVATION:-512M}
          cpus: ${CPU_RESERVATION:-1.0}
    
    # 헬스체크
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:31257/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 로깅 설정
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILES:-5}"
        compress: "true"
    
    # 보안 옵션
    security_opt:
      - no-new-privileges:true
    read_only: false  # 로그 파일 쓰기를 위해 false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # 네트워크 설정
    networks:
      - comix-network
    
    # 의존성 (필요시 데이터베이스 등 추가)
    depends_on: []

# 네트워크 정의
networks:
  comix-network:
    driver: bridge
    name: comix-network
    ipam:
      config:
        - subnet: 172.20.0.0/16

# 볼륨 정의 (영구 데이터용)
volumes:
  comix-logs:
    driver: local
    name: comix-logs
  comix-cache:
    driver: local
    name: comix-cache