# Development Docker Compose Configuration
# 개발 환경용 - 핫 리로드 및 디버깅 지원

version: '3.8'

services:
  comix-server-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: development
    image: aircomix-server:dev
    container_name: aircomix-server-dev
    restart: "no"  # 개발 중에는 자동 재시작 비활성화
    
    # 포트 매핑
    ports:
      - "${COMIX_SERVER_PORT:-31257}:31257"  # 메인 서버 포트
      - "${DEBUG_PORT:-5678}:5678"           # 디버그 포트
    
    # 개발용 볼륨 마운트
    volumes:
      # 소스 코드 마운트 (핫 리로드용)
      - "../app:/app/app:rw"
      - "../tests:/app/tests:rw"
      - "../pyproject.toml:/app/pyproject.toml:ro"
      - "../README.md:/app/README.md:ro"
      
      # 만화 컬렉션 마운트
      - "${MANGA_DIRECTORY:-../examples/sample-data}:/comix:ro"
      
      # 테스트 데이터 마운트
      - "../examples:/app/examples:ro"
      
      # 개발용 설정 및 로그
      - "./dev-config:/app/config:rw"
      - "./dev-logs:/app/logs:rw"
    
    # 개발 환경 변수
    environment:
      # 서버 설정
      - COMIX_MANGA_DIRECTORY=/comix
      - COMIX_SERVER_HOST=0.0.0.0
      - COMIX_SERVER_PORT=31257
      - COMIX_DEBUG_MODE=true
      - COMIX_LOG_LEVEL=DEBUG
      
      # Python 설정
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      
      # 개발용 설정
      - COMIX_RELOAD=true
      - COMIX_DEV_MODE=true
      
      # 파일 필터링 (개발용 - 더 관대한 설정)
      - COMIX_HIDDEN_FILES=.DS_Store,Thumbs.db
      - COMIX_HIDDEN_PATTERNS=__MACOSX,*.tmp
      
      # 인증 설정 (개발용)
      - COMIX_ENABLE_AUTH=${ENABLE_AUTH:-false}
      - COMIX_AUTH_USERNAME=${AUTH_USERNAME:-admin}
      - COMIX_AUTH_PASSWORD=${AUTH_PASSWORD:-password123}
      
      # Python 경로 설정
      - PYTHONPATH=/app
    
    # 개발용 명령어 (핫 리로드 활성화)
    command: [
      "uvicorn", 
      "app.main:create_app", 
      "--factory", 
      "--host", "0.0.0.0", 
      "--port", "31257", 
      "--reload", 
      "--reload-dir", "/app/app",
      "--log-level", "debug"
    ]
    
    # 개발용 헬스체크 (더 빠른 간격)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:31257/health"]
      interval: 15s
      timeout: 5s
      retries: 2
      start_period: 30s
    
    # 개발용 네트워크
    networks:
      - aircomix-dev-network
    
    # 개발용 보안 설정 (더 관대함)
    security_opt:
      - no-new-privileges:true
    
    # stdin 및 tty 활성화 (디버깅용)
    stdin_open: true
    tty: true

# 개발용 네트워크
networks:
  aircomix-dev-network:
    driver: bridge
    name: aircomix-dev-network
    ipam:
      config:
        - subnet: 172.21.0.0/16

# 개발용 볼륨
volumes:
  dev-cache:
    driver: local
    name: aircomix-dev-cache