name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unrar-free

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Verify installation
      run: |
        python -c "import app; print('App module imported successfully')"
        python -c "import pytest; print('Pytest imported successfully')"

    - name: Create test manga directory
      run: |
        mkdir -p /tmp/test-comix
        echo "test" > /tmp/test-comix/test.txt

    - name: Debug test environment
      run: |
        echo "=== Python version ==="
        python --version
        echo "=== Installed packages ==="
        pip list
        echo "=== Project structure ==="
        find . -name "*.py" | head -20
        echo "=== Test directory ==="
        ls -la tests/ || echo "No tests directory"
        
    - name: Run tests with pytest
      env:
        COMIX_MANGA_DIRECTORY: /tmp/test-comix
        COMIX_DEBUG_MODE: true
        PYTEST_CURRENT_TEST: true
      run: |
        echo "=== Running pytest ==="
        python -m pytest tests/ -v --tb=short

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.11'
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run linting
      continue-on-error: true
      run: |
        echo "=== Black 포매팅 체크 ==="
        black --check app/ tests/ || echo "❌ Black formatting issues found"
        
        echo "=== isort import 정렬 체크 ==="
        isort --check-only app/ tests/ || echo "❌ Import sorting issues found"
        
        echo "=== flake8 린팅 ==="
        flake8 app/ tests/ --max-line-length=88 --extend-ignore=E203,W503 || echo "❌ Flake8 issues found"
        
        echo "=== mypy 타입 체크 ==="
        mypy app/ --ignore-missing-imports || echo "❌ MyPy issues found"
        
        echo "✅ Linting completed (some issues may exist)"